<?php

    function szovegeskepesoldal()
    {
        return '<h1>Képes szöveges oldal</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eget commodo risus. Fusce iaculis ultricies sem, at rhoncus lorem porttitor eget. Duis pharetra erat sit amet sapien rutrum blandit. Praesent eget ligula velit. Nullam sagittis non massa sit amet lobortis. Morbi in pretium magna. Pellentesque sit amet diam elit. Suspendisse egestas neque tellus, sit amet ullamcorper arcu aliquet a. Curabitur blandit magna neque, consequat sollicitudin nibh iaculis non. Morbi lobortis tincidunt lobortis. Mauris vulputate, purus et commodo placerat, elit est consectetur mauris, vitae elementum odio sapien eget dolor. In quis odio sit amet risus fringilla imperdiet.

Nulla ac bibendum mi, sit amet posuere nisl. <img src="npr.brightspotcdn.jpg" class=" float float-start w-25 m-2">Pellentesque ac gravida lacus, ut consectetur metus. Sed sit amet nisl lorem. Pellentesque tortor ligula, pulvinar vel accumsan convallis, sodales vel elit. Nulla ac placerat velit, quis venenatis lorem. Aliquam id vestibulum arcu. Aliquam ac justo velit. Quisque sit amet tellus commodo, mattis metus quis, tempor turpis. Praesent quis lectus id leo pharetra rutrum consequat a nibh. Sed eget elit posuere, eleifend erat ac, aliquam diam. Vivamus in scelerisque elit. Duis nisl lacus, rutrum ut dolor quis, venenatis aliquam lectus. Nunc in lacinia diam, ut suscipit nisl.

Morbi sodales rutrum nisi, ac fringilla ligula viverra sit amet. Etiam consectetur nibh urna, auctor iaculis enim sagittis vel. <img src="lord-of-the-rings-memes-cover_675.jpg" class=" float float-end w-25 m-2"> Fusce consequat, neque non malesuada tempor, nibh sapien faucibus tellus, at sodales urna neque id enim. Donec lacus sem, interdum sit amet fringilla non, lobortis quis dolor. Nam sollicitudin lacus ac purus sollicitudin, eget consectetur felis rhoncus. Vivamus eu posuere sem. Integer sagittis ultrices leo nec volutpat. Nulla fermentum, lorem sit amet porta finibus, sapien massa euismod erat, sed pulvinar tellus eros non arcu. Nam sollicitudin sapien dolor, eu bibendum arcu ullamcorper eu. Vestibulum dignissim augue eget nisl bibendum, sit amet fringilla nunc dictum. Nulla non dolor vehicula, ullamcorper est non, auctor lectus. Sed enim quam, auctor fringilla ipsum nec, suscipit porttitor ipsum. Sed congue sem vel ipsum laoreet, tempor venenatis odio ultrices. Nullam cursus, justo at hendrerit tincidunt, augue quam vehicula libero, sit amet maximus dui dolor quis purus. Nunc porta diam eu tincidunt eleifend. Morbi at vestibulum mauris.

Curabitur felis purus, venenatis at euismod sit amet, scelerisque congue lorem.<img src="758404ebc522ce0beff7f02e59fdaf47.jpg" class=" float float-start w-25 m-2"> Vivamus id tortor sed sem lacinia hendrerit. Duis tellus eros, fermentum in convallis vitae, sollicitudin quis nibh. Pellentesque a blandit dolor, ut consequat orci. Aliquam blandit diam urna, vel ultricies dolor egestas nec. Integer sit amet molestie arcu. Aliquam varius erat quis nulla fringilla, a convallis ipsum pretium. Ut dapibus erat in neque ultrices, ac pulvinar mauris vehicula. Praesent lobortis eget enim in tincidunt. Phasellus pretium elit ut quam maximus, et dignissim nisl sollicitudin. Etiam nec turpis vitae orci varius sodales. Ut massa lacus, accumsan nec efficitur vel, euismod ut erat. Donec tempor rutrum orci a dignissim. Integer gravida euismod ante, sed lobortis elit ullamcorper at. Ut non diam ac nunc eleifend malesuada. In dapibus lacinia risus, eget porta nibh iaculis non.

Nam aliquam eu nisl sit amet placerat. Proin sed libero ut magna ultricies imperdiet iaculis eu neque. Vivamus pulvinar libero non justo eleifend, bibendum venenatis massa pretium. Donec leo enim, lobortis malesuada mattis sed, bibendum a diam. Integer condimentum turpis quis tempor porta. Etiam eget rhoncus ipsum, ut feugiat tellus. Vestibulum quis elit vitae sem lobortis sagittis non at libero.

Cras a erat eleifend, auctor turpis efficitur, blandit metus.  Quisque vel volutpat augue, sed aliquam quam. Proin iaculis nulla ut dapibus malesuada. Vivamus eget erat placerat, convallis diam quis, laoreet est. Donec a neque tristique, sagittis ante eget, fermentum mi. Quisque pretium leo ut neque laoreet, eu posuere nisi eleifend. Aliquam facilisis orci ut tempor aliquam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam eget est urna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce a scelerisque nibh. Aliquam eu lorem molestie, interdum mauris non, ultricies lectus. Aliquam ut vehicula ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. </p>';
    }


?>