<?php

    function aloldal()
    {
        return '<div class="col-12">
            <h1>Szöveges képes aloldal</h1>
            <p class="text-justify">Cras vestibulum varius lacus, vitae dictum sapien aliquet id. Nulla sed faucibus lacus. Cras nec quam placerat, eleifend nisi nec, vulputate sem. Donec commodo risus et ante vestibulum interdum. Cras sed dui vestibulum, pretium magna sed, mollis mi. Sed et dui ac augue tristique gravida. Curabitur gravida tellus eros, at eleifend enim semper non.

Duis in ipsum venenatis, iaculis erat ac, feugiat lorem. Vestibulum tristique ex sed placerat varius. Maecenas in ipsum orci. Vestibulum efficitur at nisl eu malesuada. Morbi eu consequat leo, vel volutpat dui. Proin lacinia consequat justo eget aliquet. Curabitur molestie, libero ac pretium laoreet, mauris dui laoreet libero, ac bibendum nisl lorem vitae mauris. Morbi bibendum volutpat aliquam.<img src="./2906.webp" class="float float-start w-25 p-2">Quisque bibendum justo id mi tincidunt, molestie dignissim nulla suscipit. Vestibulum vel pretium ex. Fusce varius nisi eget libero mattis pulvinar eu a mi. Cras quis pellentesque nibh, et varius odio. Morbi auctor quis nisl ac posuere. In malesuada congue libero, vehicula hendrerit eros aliquam sed. Morbi scelerisque, nibh nec volutpat tempor, orci nisl tincidunt nulla, vel condimentum felis nibh vitae lectus. Vivamus sit amet urna velit. Mauris consectetur, neque vitae hendrerit maximus, mauris dui pharetra neque, ac facilisis felis diam ac ante. In a efficitur nibh. Phasellus dignissim tortor nunc, vel dictum dolor tempor ac. Maecenas at velit sem. Sed feugiat sapien sollicitudin, dapibus massa mollis, accumsan mauris. Vivamus a eros vel nunc ornare pretium eget sit amet massa. Nam ultricies arcu ac augue tincidunt, ut vulputate felis gravida. Fusce eu lacinia justo, vitae hendrerit ipsum. Ut porttitor velit lorem, quis commodo magna luctus nec. Pellentesque accumsan leo ultrices ante dignissim elementum. Duis in facilisis nunc. Nam vitae ultrices quam. Vestibulum justo dui, aliquet et ultrices eu, varius sit amet velit. Vivamus euismod finibus urna, vitae suscipit nibh molestie et. Etiam ligula nisi, tempor non libero ac, congue hendrerit ligula. Praesent feugiat dictum suscipit. Aenean dolor felis, consectetur id tellus eget, condimentum dapibus dolor.<img src="758404ebc522ce0beff7f02e59fdaf47.jpg" class="float float-end w-25 p-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis congue sem. Aliquam erat volutpat. Vivamus a ante quis dolor placerat suscipit. Curabitur ullamcorper ante et enim porttitor rutrum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut lacus ligula, porta ac elit vitae, tempus commodo ipsum. Quisque id justo eget nunc laoreet malesuada consectetur at tellus. Duis egestas venenatis varius. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nunc vestibulum velit in velit condimentum viverra.

Duis eu iaculis lacus, non tincidunt justo. Ut eget rutrum velit. Maecenas laoreet tristique lacinia. Integer non nisi vitae lacus malesuada ultrices.</p><p> Praesent metus leo, tempor nec tortor eget, scelerisque posuere turpis. Nulla semper id nisl consequat convallis. Nulla quis velit volutpat, imperdiet tortor a, volutpat nibh. Proin efficitur, ex ut rutrum mollis, lectus nisi auctor nisi, non scelerisque urna arcu sed enim. In non lectus porttitor, laoreet nunc eget, dignissim turpis. Nulla aliquam dui vitae nunc eleifend aliquam.</p><p> Nulla facilisi. Vestibulum nibh leo, tempor nec enim ut, ultrices convallis velit. Nam eleifend neque ac lacus accumsan, bibendum iaculis risus maximus. Nulla ut convallis dolor. In fermentum est pulvinar imperdiet laoreet. Nulla malesuada neque eu odio placerat facilisis. Vivamus non ligula purus. Duis sit amet urna tristique felis molestie mattis. In eu leo eu nisi placerat vulputate eget sed erat. Sed placerat purus id est facilisis, sed egestas diam laoreet.

Pellentesque ullamcorper lacus ac condimentum ultricies. Pellentesque arcu orci, sodales id venenatis at, dictum vulputate lacus. Curabitur et ante nunc. Morbi sed blandit lectus. Donec vel turpis erat. Mauris id imperdiet risus. Quisque ultricies dolor mi, a cursus leo condimentum non. Nulla vel diam vitae erat egestas aliquam vitae eu dolor.<img src="leonardo-dicaprio-cheers-meme-template-full-45246ac0.webp" class="float float-start w-25 p-2">Ut aliquam vitae sem et aliquam. Sed lobortis leo sed sem lobortis, sit amet laoreet est interdum. Aliquam pretium lectus nisi, eu hendrerit lectus posuere eget. Vivamus euismod lorem mauris, at vulputate orci laoreet ac. Nunc id justo ante. Pellentesque sed libero vehicula ex mollis luctus at eu turpis. Vestibulum tristique urna nec lectus facilisis, sit amet luctus ligula egestas. Fusce in rutrum mi. Quisque eu metus condimentum elit finibus pellentesque ut sit amet turpis. Praesent aliquam vulputate sem at pellentesque. Nam libero lorem, luctus at ornare non, pharetra at tortor. Vivamus id vulputate purus.

Suspendisse non dolor sed orci finibus dignissim ac vel metus. Aliquam eu cursus nunc. Nullam iaculis, dui quis maximus feugiat, arcu erat porttitor nisi, at sollicitudin erat ante vitae mi. Aliquam erat volutpat. Cras ac tellus non leo placerat aliquet. Quisque sollicitudin elit augue, eu tempor felis tristique quis. Aenean finibus quis quam non venenatis. Vestibulum aliquam vehicula mi. Nulla cursus varius mi at interdum. Aenean posuere finibus ligula, quis consequat sem scelerisque non. Pellentesque accumsan ipsum in ipsum scelerisque, eu varius sapien congue. Curabitur sollicitudin nunc ac nibh dignissim, sit amet fermentum felis fermentum. Maecenas et dolor ac enim vehicula tincidunt.</p><p> Nunc sit amet mauris purus. Sed commodo faucibus purus et luctus. Nunc in risus at justo dapibus gravida vel id ante.</p>
        </div>';
    }

?>